CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS doctor_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS patient_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS prescription_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS health_metric_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS attachment_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS assistant_seq START WITH 1 INCREMENT BY 1;